M    __init__.py * log to stderr. introduces a bug: when broken pipe, *lots* of these appear:
Traceback (most recent call last):
  File "/usr/lib/python2.3/logging/__init__.py", line 682, in emit
      self.flush()
  File "/usr/lib/python2.3/logging/__init__.py", line 661, in flush
      self.stream.flush()
IOError: [Errno 32] Broken pipe

  will be fixed later.